### ISSUE TITLE
Decide which Galaxy config files need a ConfigMap

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#3]
Galaxy's config dir has over 30 `.sample` configuration files. We need to select a subset of those that are likely to be edited/configured as part of the Helm chart. Those will then be templated as ConfigMaps. The rest, we can just remain as `.sample` and used with the default values.

**Comment by nuwang** [comment]
We could make all 30 editable through configmaps, but only if a value is set.
The entirety of the 30 galaxy configs may need to be modelled as a single config map, which is then mounted into the /galaxy/config directory.
If a value is set for that configmap entry in the values file, only then do we render out the corresponding file through the configmap. This way, most settings can default to the .sample file, since the override file will never exist.

**Comment by afgane** [comment]
Right, but also we want to pick a subset that will be templated with values specified in the `values.yaml` file so they can be edited without having to edit the XML (via a ConfigMap)? Those are the ones I think need selection.

**Comment by nuwang** [comment]
We can start off on an as-needed-basis? Say start with values.galaxy_conf, and then use values.galaxy_conf.raw to set the passthrough file, or individual properties that are rendered through our template. Since that mechanism is general, we can do that incrementally for any file we want over time. Probably all we need urgently are galaxy.yml, job_conf.xml and tool_conf.xml?

**Comment by nuwang** [comment]
Hmm... Was just wondering whether that would conflict with our UI based editor though? For example, if galaxy_conf.raw is set, does our editor become non-functional? Perhaps we need to think of the entire value as a single large value? E.g. if .Values.job_conf is set, we use that, if not, we use some default template. There is no notion of a raw passthrough value at all. The disadvantage with this option is that you either set the entire value, or none at all. However, the advantage is that there's always only one "value" to deal with. How we understand that value, render it in a UI etc. is up to us.

**Comment by afgane** [comment]
I was just looking through the list of config files and am wondering if we really need to template anything other than `galaxy.yml`, especially for the time being. 

We will set `job_conf.xml` to use the K8S runner and that will really be the only runner available for the immediate future. Unless that needs some cluster-specific configuration (in which case we'll need to template it), we shouldn't be needing to edit that file for now? We can perhaps use`tool_destinations.yml` to define resource rules? (I just now noticed that file exists.)

`tool_conf.xml` seems similar. We can either do nothing and just assume the default toolset or provide our flavor as a plain text config map to make it easier to modify (but we can do that at any point). Why would a user manually edit `tool_conf.xml`? The bulk of tools will (hopefully) come from the CMVFS with its own `shed_tool_conf.xml`. If we want a flavor of that that's different from the default one being used on Main, we can just add our own `shed_tool_conf.xml` to the CVMFS. One concern here is that once that file is updated, all instances (old and new) will automatically adopt the new toolset. 

Tools installed on the cluster will go into their own, local `shed_tool_conf.xml`. Galaxy creates that file but it will need to be persisted somewhere, along with the accompanying tool install database (or if we don't use the install database, the main database will take care of that). 

Actually, as long as we have a model for how a `yaml` file is edited and how an `xml` file is edited, we should be ok as we can always add more files, which cycles back to the most recent comment. If we don't need to template any files other than `galaxy.yml`, I feel we can have the form editor available only for `galaxy.yml` and the rest would be a plan text editor that renders the complete XML and the ConfigMap places the XML verbatim on the disk. So each edit would just be the `.raw` equivalent. Mixing and matching the values from a template and a user seems like it is likely to get us into parsing hell.

**Comment by nuwang** [comment]
Yes, that sounds sensible to me too. Handling yaml files in helm is pretty natural anyway, so if values are set directly, we should be able to do something about it, even if it's complex and hierarchical (although we did run into problems with cloudman bootstrap data, and had to encode it etc)

XML is not so natural to pass through to a values file, because new lines etc. are problematic. The other option is to pass in the values by writing them out to a file, which may be a workaround.

I think we just need to test out the latter option, and see whether we can make it work well. If so, it seems like the logical way forward.

**Comment by almahmoud** [comment]
With a model similar to this attempt: https://github.com/CloudVE/galaxy-kubernetes/pull/4/commits/1acf7e5a37ca2bb4341504b69baacfe50f011797 we can template only the config files that we want, but still give the user the option to specify any config file by specifying its path and contents and have it be automatically added to the (single) configmap

**Comment by afgane** [comment]
Given the discussion and the above linked issue, providing values for `galaxy.yml` and `job_conf.xml` seems like a good starting point that is then extensible as the system gets more features and gets.

Closing this for now on that note.

**Comment by afgane** [comment]
Following today's meeting (https://github.com/CloudVE/mgmt/blob/master/weekly-meetings-agenda.md#2019-05-28), we'll also need to add a template for the `integrated_tool_panel.xml` that contains all the desired sections only. The list of tools will be populated automatically by Galaxy as the process starts up.
