### ISSUE TITLE
Compose a minimal version of the Chart values file

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#35]
For development purposes in particular but also for local installations where a toolset different from that of Galaxy Main is desired, we should have a `values.yaml` file that uses pretty much only the default Galaxy values, omits the integration with the CVMFS, but retains the K8S job runner.

**Comment by almahmoud** [comment]
Although not a top priority, I believe this will be easier with custom init containers so that we can change what files get copied and/or created directly from the values file, thus I will also do a basic version of https://github.com/CloudVE/galaxy-kubernetes/issues/30 while making this `values-minimal.yaml` file

**Comment by nuwang** [comment]
Closed by: https://github.com/CloudVE/galaxy-kubernetes/commit/ee1b3eb3341149ebdfb5a720bc9fd4e6173f504b
