### ISSUE TITLE
Get the Galaxy chart working on GKE by running kubectl command manually

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#6]
The process should be as follows:
- [x] Launch a GKE cluster (need k8s version 1.13, which installs only via `gcloud` command)
- [x] Install Helm (supposedly does not work on GKE v 1.13)
- [x] Add CloudVE helm charts repo to helm repos (will need to add packaged galaxy chart to https://github.com/CloudVE/helm-charts/tree/master/charts)
- [x] Install a persistent volume + claim for postgres (as per Galaxy chart installation Readme) 
- [x] Install the Galaxy chart
- [x] Test shutdown and recreate

**Comment by almahmoud** [comment]
Some helpful notes:
- Setting up `gcloud` command-line: https://cloud.google.com/sdk/docs/
- Creating a gke cluster with k8s 1.13: `gcloud container clusters create [name] --cluster-version=1.13.5-gke.10 --enable-kubernetes-alpha --no-enable-autorepair --disk-size=30 --num-nodes=2`
- Generate k8s manifests with helm (no need for a tiller pod): `mkdir [dir-name] && helm template --name [release-name] --output-dir ./[dir-name] .`. You can then do `kubectl create -f [dir-name]/galaxy/templates/` to run all. The only difference from running `helm install` directly would be the order in which things are created. If you want to do it in the same order, you would have to manually create the resources. Here is the Helm order: https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go#L29
- Note: When creating a cluster with `gcloud` while having docker for mac running, the context for k8s will change to the gke cluster. i.e. running `kubectl` even locally will actually deploy in the GKE cluster, so there is no need to copy the files to the GKE console or otherwise setup helm there to deploy the k8s manifests.
- Note 2: You can `kubectl create -f dashboard.yml` then `kubectl proxy` locally (when the context is set to the GKE cluster) then access the dashboard on `http://localhost:8001` which is generally more helpful than the GKE dashboard (especially for logs) imo.

**Comment by almahmoud** [comment]
Valid `cluster-version` for GKE is now `1.13.5-gke.10` instead of `1.13.5-gke.7`

**Comment by almahmoud** [comment]
I did some more testing on GKE the past few days.
Some notes in case they are helpful to someone who knows the chart (especially postgres) better than me:
- The (new) `initdb-configmap` has a name that varies based on the release, but it is referenced directly as `galaxy-initdb` (I believe from `.Values.initdbScriptsConfigMap` in other places). A quick fix is to just hard code the name of the configmap for now: https://github.com/CloudVE/galaxy-kubernetes/pull/8
- The `init-chmod-data` container has commands: `chown -R 1001:1001 /bitnami` as well as `if [ -d /var/lib/postgresql/data/data ]; then chmod  0700 /var/lib/postgresql/data/data; fi`. The first one errors out because `chown: cannot access '/bitnami': No such file or directory`, so I manually removed that part  and that seemed to have fixed the problem (no more error logs in that container).
- The `gpsql` container errors out with message `mkdir: cannot create directory ‘/var/lib/postgresql/data/pgdata’: Permission denied`. One thing to note is that this is the specified `.Values.postgresqlDataDir`, but the `init-chmod-data` container specified above is currently chmod-ing the`{{ .Values.persistence.mountPath }}/data` directory it seems, with the default `mountPath` currently specified to `/var/lib/postgresql/data` (not sure if this is intended and both `/var/lib/postgresql/data/data` and `/var/lib/postgresql/data/pgdata` directories should exist or if it's a mismatch that needs to be fixed.

Some things that I tried:
- Removing the `chown /bitnami` (always). Result: no more error logs in the `init-chmod-data` container
- Setting `postgresqlDataDir: "/var/lib/postgresql/data/data"` and `persistence.mountPath: "/var/lib/postgresql/data"` and manually changing the command to `if [ -d /var/lib/postgresql/data ]; then chmod -R 0700 /var/lib/postgresql/data; fi` OR `if [ -d /var/lib/postgresql/data/data ]; then chmod 0700 /var/lib/postgresql/data/data; fi`. Same result in both cases: still having `mkdir: cannot create directory ‘/var/lib/postgresql/data’: Permission denied` in the `gpsql` container
- One thing that did change the error message was setting `.Values.postgresqlDataDir=.Values.persistence.mountPath=/var/lib/postgresql/data`. Even without changing anything in `init-chmod-data` container (i.e. still having the `/bitnami` error), the log message in the `gpsql` container becomes:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
 The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".
 Data page checksums are disabled.
 initdb: could not access directory "/var/lib/postgresql/data": Permission denied
```
Changing the `init-chmod-data` container command to remove the `chown /bitnami` part and have `if [ -d /var/lib/postgresql/data ]; then chmod 0700 /var/lib/postgresql/data; fi` removes the `init-chmod-data` container error message as before, but does not affect the `gpsql` container whatsoever.

**Comment by almahmoud** [comment]
P.S.: The above was all done by having the kubectl context pointing to a GKE 1.13.10 cluser. I'm pasting the main commands used in case it's helpful:
```
# from within galaxy-kubernetes/galaxy directory
helm template --name alex-gxy --output-dir am-alex-testing-manifests/ .
kubectl create -f postgres-pv.yaml
kubectl create -f am-alex-testing-manifests/galaxy/templates/configmap-initdb.yaml
kubectl create -f am-alex-testing-manifests/galaxy/charts/postgresql/templates/
kubectl create -f am-alex-testing-manifests/galaxy/templates/
```
The commands for the `init-chmod-data` container changed in: `am-alex-testing-manifests/galaxy/charts/postgresql/templates/statefulset.yaml`

Also, found this 
The bottom part might or might not be relevant: https://github.com/kubernetes/kubernetes/issues/2630#issuecomment-485885319

**Comment by afgane** [comment]
Re. the `initdb-configname`: Nuwan's PR to the upstream chart should fix that: https://github.com/helm/charts/pull/13705

**Comment by nuwang** [comment]
I've already fixed some of this in the chart. Let me push them in (was waiting for the upstream PR to go through)

**Comment by almahmoud** [comment]
Re: slack conversation

Helm v2.8.0 works on GKE with alpha cluster 1.13.5(.10).
From GKE cloud console to get it working:
First time:
`wget https://storage.googleapis.com/kubernetes-helm/helm-v2.8.0-linux-amd64.tar.gz && tar zxfv helm-v2.8.0-linux-amd64.tar.gz && cp linux-amd64/helm . && kubectl create clusterrolebinding user-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account) && kubectl create serviceaccount tiller --namespace kube-system && kubectl create clusterrolebinding tiller-admin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:tiller && ./helm init --service-account=tiller && ./helm update`
Any time you change clusters:
`kubectl create clusterrolebinding user-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account) && kubectl create serviceaccount tiller --namespace kube-system && kubectl create clusterrolebinding tiller-admin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:tiller && ./helm init --service-account=tiller && ./helm update`
(and run from the local binary `./helm`

Will test newer versions and a better setup later, but thought i'd quickly put this here before bed

**Comment by almahmoud** [comment]
Works very well on GKE so closing this issue
