### ISSUE TITLE
Create ConfigMaps for Galaxy files

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#7]
Based on the discussion in #3, it seems we need only `galaxy.yml` and `job_conf.xml` for the time being. However, more generally, it's really two types of files we're after: `yaml` and `xml` so the idea is to introduce a model for supporting those two file types and let the user define any config files they'd like. 

This is the approach that was implemented in #5.

**Comment by almahmoud** [comment]
Done with merge https://github.com/CloudVE/galaxy-kubernetes/pull/5 . Accepting raw content into any file or yaml contents. All contents get run through `tpl` so placeholders from within the `values.yaml` file are accepted under the content key.

**Comment by almahmoud** [comment]
Re-opening this issue, given the development with duplicate keys (`static-map` at least one of them) not being accepted if we treat the content as real yaml. 
This is a somewhat relevant issue: https://github.com/galaxyproject/ansible-galaxy/issues/42
Moving forward for the galaxy conf files, in order to keep our current (or similar) structure where the contents get run as a whole through tpl, we have to somehow avoid treating the contents as a map at any point while referencing them (because the first time that they get read as a `map[...]` object, all the duplicate keys will be removed and any further casting is irrelevant.
One easy way to fix this, is treating the content as one multi-line string, as done temporarily in: https://github.com/CloudVE/galaxy-kubernetes/commit/d6379fbf7b476c53fa829fe257389d5a70de5405#diff-bcfeaa7e206ee9dfc036e44b77313133R35
However, this method removes the possibility to specify values directly by key.
The only idea I have so far is to have the different values be listed under one key:
```
static-map:
  - first
  - second
```
and expand it when running tpl as:
```
static-map: first
static-map: second
```
in the configmap data (and therefore in the actual `galaxy.yml` file).
However, this makes it so that the contents of `.Values.configs.galaxy.yml` are not directly put into the file, which means, we need to decide when this processing happens (only for certain keys or for any list. If the first, then we'd have to document the keys and explicitly state what is being transformed, how and when, and it adds a layer of helm-specific configuration that the admin would have to know, which kind of defeats the purpose of putting the raw contents so that they can configure the helm chart as if they are configuring `galaxy` directly. If the second, then we'd have to figure out 1) whether there are any keys in the configuration that need a true list that should not be converted into duplicate keys and 2) how to both expand the values and process them through tpl when necessary.
I'll give it a try today and tomorrow and see how easy either option is, but neither seems ideal, so any new ideas/input would be appreciated.

**Comment by nuwang** [comment]
Enis and I briefly described the possibility of sending it in as a multi-line string, and then doing the handling on the client side. However, that may not work either, because whichever way we do this, this is invalid yaml and won't parse.

**Comment by afgane** [comment]
The final decision was to just treat each ConfigMap as a multi-line string and deal with the invalid yaml downstream.
